### ISSUE TITLE
Feature request: define inaccessible destinations

### ISSUE THREAD

**Issue by x-qq** [niklata/muonsocks#1]
Currently a client connecting to muonproxy running on a remote server can perform connections to ports bound to 127.0.0.x addresses on that server, for example:

```
curl -x socks4://remote.host:1080 http://127.0.0.1:9999/
```

will send an HTTP request to the service listening on 127.0.0.1:9999 on `remote.host` that would not otherwise be accessible.

This could potentially be surprising for the server operator, and/or a security issue.

It would be nice to be able to define a list of ranges of addresses that should not be accessible via the proxy service, possibly with 127.* addresses being on that list by default.

**Comment by niklata** [comment]
This is a very reasonable feature and I agree that 127.0.0.0/8 should be deny-by-default.  I will add it soon.

**Comment by niklata** [comment]
Commit 7edc8bf4adbc should add a deny-by-default for both ipv4 and ipv6 loopback.

It's easy enough to add further bans (or remove the default ones) by editing the source and recompiling.  I haven't added command line switch options simply because it becomes somewhat cumbersome with ipv4 and ipv6, requiring either two switches, or a parser to detect whether a address/mask string corresponds to a v4 or a v6 address, and requiring different switches to get rid of the default loopback bans if that would ever make sense.
